#!/bin/bash

#-----------------------------------------------------------------
# just assemble the asm source generated by compiling the C source
#-----------------------------------------------------------------
../bin/gpasm -c main.asm
